# Generated by Django 3.0.5 on 2020-08-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('ordertotal', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('orderconfiremd', 'orderconfiremd'), ('cancelled', 'cancelled'), ('completed', 'completed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20)),
                ('type', models.CharField(choices=[('1', 'count'), ('2', 'kg'), ('3', 'grams')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='orderedcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('pidtotal', models.FloatField()),
                ('orderedid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orders')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.product')),
            ],
        ),
    ]
