# Generated by Django 3.0.5 on 2020-08-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('count', 'count'), ('kg', 'kg'), ('grams', 'grams')], max_length=20),
        ),
    ]
