# Generated by Django 3.1 on 2020-08-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200817_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='types',
        ),
    ]
