# Generated by Django 3.0.5 on 2020-08-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200819_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='setcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_cart_value', models.FloatField()),
                ('silveroff', models.FloatField()),
                ('goldenoff', models.FloatField()),
                ('platinumoff', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='market_price',
        ),
        migrations.AddField(
            model_name='product',
            name='our_price',
            field=models.FloatField(default=72),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('orderconfiremd', 'orderconfiremd'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
