# Generated by Django 3.0.5 on 2020-08-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200821_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='setcart',
        ),
    ]
