# Generated by Django 3.0.5 on 2020-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_delete_setcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='setcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_cart_value', models.FloatField()),
                ('silveroff_value', models.FloatField()),
                ('goldenoff_value', models.FloatField()),
                ('platinumoff_value', models.FloatField()),
                ('silveroff_percentage', models.IntegerField()),
                ('goldenoff_percentage', models.IntegerField()),
                ('platinumoff_percentage', models.IntegerField()),
            ],
        ),
    ]
