# Generated by Django 3.0.5 on 2020-08-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_setcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
