# Generated by Django 3.0.5 on 2020-08-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orders_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderfinaltotal',
            field=models.FloatField(default=0),
        ),
    ]
