# Generated by Django 3.0.5 on 2020-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orders_orderfinaltotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits', 'fruits'), ('vegetables', 'vegetables'), ('groceries', 'groceries')], default='vegetables', max_length=60),
            preserve_default=False,
        ),
    ]
