# Generated by Django 3.0.5 on 2020-08-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedcart',
            name='quantity_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
