# Generated by Django 3.0.5 on 2020-08-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200823_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='setcart',
            name='offer_on_or_off',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=10, null=True),
        ),
    ]
