# Generated by Django 3.0.5 on 2020-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_setcart_offer_on_or_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='setcart',
            name='phoneno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
