# Generated by Django 3.0.5 on 2020-08-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_setcart_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('our_price', models.FloatField()),
                ('market_price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('types', models.CharField(default='flower', max_length=20)),
                ('category', models.CharField(choices=[('kg', 'kg'), ('grams', 'grams'), ('mulam', 'mulam'), ('maalai', 'maalai'), ('bunch', 'bunch')], max_length=60)),
            ],
        ),
    ]
