# Generated by Django 3.0.5 on 2020-08-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_flower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.CharField(choices=[('kg', 'kg'), ('grams', 'grams'), ('mulam', 'mulam'), ('maalai', 'maalai'), ('bunch', 'bunch'), ('count', 'count')], max_length=60),
        ),
        migrations.AlterField(
            model_name='orderedcart',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.flower'),
        ),
    ]
