# Generated by Django 3.0.5 on 2020-08-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_remove_orderedcart_pid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderedcart',
        ),
    ]
