# Generated by Django 3.0.5 on 2020-08-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_delete_orderedcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderedcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_type', models.CharField(max_length=30, null=True)),
                ('quantity', models.FloatField()),
                ('pidtotal', models.FloatField()),
                ('orderedid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orders')),
                ('pfid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.flower')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.product')),
            ],
        ),
    ]
