# Generated by Django 3.0.5 on 2020-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
