# Generated by Django 3.0.5 on 2020-08-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20200827_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='groceries_category',
            field=models.CharField(choices=[('nuts', 'nuts'), ('dhaals', 'dhaals'), ('oils', 'oils'), ('kitchen-cleaners', 'kitchen-cleaners')], max_length=60, null=True),
        ),
    ]
