# Generated by Django 3.1 on 2020-08-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20200830_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='groceries_category',
            field=models.CharField(blank=True, choices=[('nuts', 'nuts'), ('dhaals', 'dhaals'), ('oils', 'oils'), ('kitchen-cleaners', 'kitchen-cleaners')], max_length=60, null=True),
        ),
    ]
