# Generated by Django 3.0.5 on 2020-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20200903_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='groceries_category',
            field=models.CharField(blank=True, choices=[('nuts', 'nuts'), ('dhaals', 'dhaals'), ('oils', 'oils'), ('Home-care', 'Home-care'), ('Baby-care', 'Baby-care'), ('Personal-care', 'Personal-care'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks')], max_length=60, null=True),
        ),
    ]
