# Generated by Django 3.0.5 on 2020-09-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20200907_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_avail',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
