# Generated by Django 3.0.5 on 2020-09-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_product_product_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='product_avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_avail',
            field=models.BooleanField(default=True),
        ),
    ]
