# Generated by Django 3.0.5 on 2020-09-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_auto_20200909_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='orderedcart',
            name='orderedid',
        ),
        migrations.RemoveField(
            model_name='orderedcart',
            name='pfid',
        ),
        migrations.RemoveField(
            model_name='orderedcart',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='area',
        ),
        migrations.DeleteModel(
            name='setcart',
        ),
        migrations.DeleteModel(
            name='flower',
        ),
        migrations.DeleteModel(
            name='orderedcart',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
