# Generated by Django 3.0.5 on 2020-09-09 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0031_auto_20200909_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('feedbackdata', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('our_price', models.FloatField()),
                ('market_price', models.FloatField()),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('types', models.CharField(default='flower', max_length=20)),
                ('category', models.CharField(choices=[('kg', 'kg'), ('grams', 'grams'), ('mulam', 'mulam'), ('maalai', 'maalai'), ('bunch', 'bunch'), ('count', 'count')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('our_price', models.FloatField()),
                ('market_price', models.FloatField()),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('types', models.CharField(choices=[('count', 'count'), ('kg', 'kg'), ('grams', 'grams')], max_length=20)),
                ('category', models.CharField(choices=[('fruits', 'fruits'), ('vegetables', 'vegetables'), ('groceries', 'groceries')], max_length=60)),
                ('groceries_category', models.CharField(blank=True, choices=[('nuts', 'nuts'), ('dhaals', 'dhaals'), ('oils', 'oils'), ('Home-care', 'Home-care'), ('Baby-care', 'Baby-care'), ('Personal-care', 'Personal-care'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks')], max_length=60, null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='setcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_on_or_off', models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=10, null=True)),
                ('minimum_cart_value', models.FloatField()),
                ('silveroff_value', models.FloatField()),
                ('silveroff_percentage', models.IntegerField()),
                ('goldenoff_value', models.FloatField()),
                ('goldenoff_percentage', models.IntegerField()),
                ('platinumoff_value', models.FloatField()),
                ('platinumoff_percentage', models.IntegerField()),
                ('phoneno', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('ordertotal', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('orderconfirmed', 'orderconfirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', max_length=20)),
                ('offer', models.IntegerField(default=0)),
                ('orderfinaltotal', models.FloatField(default=0)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.service')),
            ],
        ),
        migrations.CreateModel(
            name='orderedcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_type', models.CharField(max_length=30, null=True)),
                ('quantity', models.FloatField()),
                ('pidtotal', models.FloatField()),
                ('orderedid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orders')),
                ('pfid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.flower')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.product')),
            ],
        ),
    ]
