# Generated by Django 3.1 on 2020-09-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_feedback_flower_orderedcart_orders_product_service_setcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='product_avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_avail',
            field=models.BooleanField(default=True),
        ),
    ]
